### ISSUE TITLE
TypeError: must be xml.etree.ElementTree.Element, not None

### ISSUE THREAD

**Issue by nrcmkoh** [oxplot/difftr#1]
I am getting the following error message when I attempt to diff my .kjb files:

> Traceback (most recent call last):
  File "C:/difftr-master/difftr.py", line 49, in <module>
    ktr.remove(ktr.find('./order'))
TypeError: must be xml.etree.ElementTree.Element, not None

I've attached my sample files.

[sample-files.zip](https://github.com/oxplot/difftr/files/1032689/sample-files.zip)

**Comment by oxplot** [comment]
@nrcmkoh These are job files (ie KJB). See the introduction note in the [Readme](https://github.com/oxplot/difftr/blob/master/Readme.md):

> difftr finds differences between two different **Pentaho Kettle KTR** files

**Comment by nrcmkoh** [comment]
Ah, sorry about that. Any plans to support .kjb file diffing?

**Comment by oxplot** [comment]
No plans. I don't really use Pentaho or this tool anymore, so no reason to
spend time on it.
