### ISSUE TITLE
License update request

### ISSUE THREAD

**Issue by zacharynanfelt** [oxplot/difftr#2]
Mansour, 

I noticed in your last comment on an issue that you aren't actively using or maintaining this anymore.  I assume you intended it to be in the public domain as it is a public repository but I thought I would check.  Do you have an intended license for this repository?  I can add it in a pull request if you like.

Thanks,
Zach

**Comment by oxplot** [comment]
I'll add a license file today.

**Comment by oxplot** [comment]
Done: https://github.com/oxplot/difftr/commit/5ec12a73a3ed87697827dad59873469c1fe29930

**Comment by zacharynanfelt** [comment]
Awesome, thank you!
